routes:
  - path: /get_time
    func: get_time
    query-params:
      - name: name
        nullify-empty: true
  - path: /hello
    func: hello
    query-params:
      - name: name
        nullify-empty: true
