set search_path = {{.hannibalSchema}};

create table users (
  id int primary key generated by default as identity,
  username text not null unique,
  creation_time timestamptz not null,
  last_update_time timestamptz not null,
  delete_time timestamptz
);
