set search_path = {{.hannibalSchema}};

create table api_keys (
  id int primary key generated by default as identity,
  user_id int not null references users,
  digest bytea not null unique,
  creation_time timestamptz not null,
  delete_time timestamptz
);

create index on api_keys (user_id);
