set search_path = {{.hannibalSchema}};

create table deploy_keys (
  id int primary key generated by default as identity,
  user_id int not null references users,
  public_key bytea not null unique,
  creation_time timestamptz not null,
  delete_time timestamptz
);

create index on deploy_keys (user_id);
