set search_path = {{.foobarbuilderSchema}};

create table handler (
  id int primary key generated by default as identity,
  method text not null,
  pattern text not null,
  sql text not null
);

create table param_type (
  id text primary key
);

insert into param_type (id) values
  ('text'),
  ('int')
;

create table handler_param (
  id int primary key generated by default as identity,
  handler_id int not null references handler,
  position int not null,
  name text not null,
  param_type_id text not null references param_type,
  required boolean not null,
  unique(handler_id, name),
  unique(handler_id, position)
);

create function build_handler_param(
  _name text,
  _param_type_id text,
  _required boolean
) returns handler_param
set search_path = {{.foobarbuilderSchema}}
language plpgsql as $$
declare
  _result handler_param;
begin
  _result.name = _name;
  _result.param_type_id = _param_type_id;
  _result.required = _required;

  return _result;
end;
$$;

create function create_handler(
  method text,
  pattern text,
  sql text,
  params handler_param[]
) returns handler
set search_path = {{.foobarbuilderSchema}}
language plpgsql as $$
declare
  result handler;
  p handler_param;
  pos int = 0;
begin
  insert into handler (method, pattern, sql)
  values (method, pattern, sql)
  returning * into strict result;

  foreach p in array params
  loop
    pos = pos + 1;

    p.id = nextval('handler_param_id_seq');
    p.handler_id = result.id;
    p.position = pos;
    insert into handler_param values (p.*);
  end loop;

  return result;
end;
$$;

create type get_handler_result_row_param as (
  name text,
  param_type_id text,
  required boolean
);

create type get_handler_result_row as (
  method text,
  pattern text,
  sql text,
  params get_handler_result_row_param[]
);

create function get_handlers()
returns setof get_handler_result_row
set search_path = {{.foobarbuilderSchema}}
language sql as $$
  select row(
    method,
    pattern,
    sql,
    (
      select coalesce(array_agg(row(name, param_type_id, required)::get_handler_result_row_param order by position), '{}')
      from handler_param
      where handler_id=handler.id
    )
  )::get_handler_result_row
  from handler;
$$;
